--- #YAML:1.0
name:               Net-DNS-ZoneFile-Fast
version:            1.15
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::File:       0
    MIME::Base64:   0
    Net::DNS:       0.65
    Net::DNS::SEC:  0.15
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
